apiVersion: v1
entries:
  cert-manager:
  - apiVersion: v2
    appVersion: v1.21.2
    description: A Helm chart for cert-manager
    digest: 73a56e1728edd6c99f1f31082618c3259d279a76b7ebd3d4bdc5475c2442d34a
    name: cert-manager
    urls:
    - cert-manager-v1.21.2.tgz
    version: v1.21.2
  metrics-server:
  - apiVersion: v2
    appVersion: 0.9.0
    description: Metrics Server is a scalable, efficient source of container resource
      metrics for Kubernetes built-in autoscaling pipelines.
    digest: c2ca1185c01e6e7f53dd1b7d131f0c9b3fa50e003ed068b784563a1b5a3422a1
    name: metrics-server
    urls:
    - metrics-server-3.14.0.tgz
    version: 3.14.0
  traefik:
  - apiVersion: v2
    appVersion: v3.7.13
    description: A Traefik based Kubernetes ingress controller
    digest: cd7254ea853da73bdb88edc896f079b88d43ffa0bfe699fdbf21081361eac365
    name: traefik
    urls:
    - traefik-41.6.0.tgz
    version: 41.6.0
